# Generated by Django 3.0.8 on 2020-08-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirp_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postchirp',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
