# Generated by Django 3.0.8 on 2020-07-24 23:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grocery_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groceryitem', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2020, 7, 24, 23, 10, 15, 573181, tzinfo=utc))),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
