# Generated by Django 3.0.8 on 2020-07-24 18:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('grocerlist', '0002_auto_20200724_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocery_list',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 24, 18, 23, 40, 238020, tzinfo=utc)),
        ),
    ]
