# Generated by Django 3.0.8 on 2020-07-24 21:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('grocerlist', '0003_auto_20200724_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocery_list',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 24, 21, 47, 4, 766440, tzinfo=utc)),
        ),
    ]
