# Generated by Django 3.0.8 on 2020-07-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groceryitem',
            old_name='completed_date',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='groceryitem',
            old_name='completed',
            new_name='is_done',
        ),
        migrations.RemoveField(
            model_name='groceryitem',
            name='created_date',
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='complete_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
