# Generated by Django 3.0.8 on 2020-07-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlshortener',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
    ]
