# Generated by Django 2.1.7 on 2020-07-27 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlshortener',
            name='short_url',
        ),
    ]
