# Generated by Django 2.1.7 on 2020-07-27 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0002_remove_urlshortener_short_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlshortener',
            name='short_url',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
