# Generated by Django 2.1.7 on 2020-07-27 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0004_auto_20200727_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortener',
            name='short_url',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
